### ISSUE TITLE
Make the README useful

### ISSUE THREAD

**Issue by toolness** [mozilla/ceci#94]
Hey, for folks who are trying to dig into AppMaker and figure out how everything fits together, a brief description of what ceci is trying to accomplish would be really helpful. I don't mean anything as extensive as API docs... Just a paragraph, or even a sentence. And changing the Github description of the repo would be helpful too.

I'd do this myself and issue a PR, but unfortunately _I_ don't understand the purpose of ceci yet.

![ceci](http://4.bp.blogspot.com/_kwoeqBU-2wY/TPT-ozX_VOI/AAAAAAAAAAw/38I4JYbsbEA/s1600/Margritti+this+is+not+a+pipe.jpg)

**Comment by eric-brechemier** [comment]
Also, there is no cedilla on the second c, "Ceçi n'est pas une pipe", cf the picture.
